name = "fixxer"
main = "src/index.ts"
compatibility_date = "2023-03-12"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build --if-present"

[env.production]
name = "m3u8proxy-prod"
route = "*/*"
